_wandb:
    value:
        cli_version: 0.22.1
        e:
            19wpztpgqtqhgclp9bszs8v5xm2x2z4g:
                apple:
                    ecpuCores: 6
                    gpuCores: 10
                    memoryGb: 24
                    name: Apple M4
                    pcpuCores: 4
                    ramTotalBytes: "25769803776"
                    swapTotalBytes: "2147483648"
                codePath: tinker_cookbook/rl/envs/inspect/bash_codeforces.py
                codePathLocal: tinker_cookbook/rl/envs/inspect/bash_codeforces.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "494384795648"
                        used: "434308354048"
                email: volodimir1024@gmail.com
                executable: /Users/user/reward-hacking/tinker-cookbook-reward-hacking/.venv/bin/python3
                git:
                    commit: 35bf620b864efc784eea4a991033ed0934d2628f
                    remote: https://github.com/astowolfo/tinker-cookbook-reward-hacking
                host: users-MacBook-Air.local
                memory:
                    total: "25769803776"
                os: macOS-15.6.1-arm64-arm-64bit-Mach-O
                program: /Users/user/reward-hacking/tinker-cookbook-reward-hacking/tinker_cookbook/rl/envs/inspect/bash_codeforces.py
                python: CPython 3.13.7
                root: tmp/tinker-runs/bash_codeforces
                startedAt: "2025-12-05T14:18:22.371497Z"
                writerId: 19wpztpgqtqhgclp9bszs8v5xm2x2z4g
        m: []
        python_version: 3.13.7
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
            "2":
                - 1
                - 11
                - 49
                - 51
                - 95
                - 97
            "3":
                - 13
                - 16
            "4": 3.13.7
            "5": 0.22.1
            "6": 4.57.0
            "12": 0.22.1
            "13": darwin-arm64
async_config:
    value: null
base_url:
    value: null
compute_post_kl:
    value: false
enable_trace:
    value: false
eval_every:
    value: 0
evaluator_builders:
    value: []
kl_discount_factor:
    value: 0
kl_penalty_coef:
    value: 0
learning_rate:
    value: 4e-05
load_checkpoint_path:
    value: null
log_path:
    value: tmp/tinker-runs/bash_codeforces/
lora_rank:
    value: 32
loss_fn:
    value: importance_sampling
max_tokens:
    value: 2048
model_name:
    value: openai/gpt-oss-20b
num_groups_to_log:
    value: 4
num_substeps:
    value: 1
remove_constant_reward_groups:
    value: false
save_every:
    value: 20
stream_minibatch_config:
    value: null
wandb_name:
    value: openai/gpt-oss-20b
wandb_project:
    value: inspect-bash-codeforces
